// this file was generated by copilot, but doesn't work

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <stdbool.h>

#include "../../src/general/all.h"
#include "../../src/sieve/sieve_extend_continuePattern.h"

int bit_get(bitword_t* bitstorage, counter_t index) {
    return (bitstorage[wordindex(index)] >> bitindex_calc(index)) & 1;
}

void bit_set(bitword_t* bitstorage, counter_t index) {
    bitstorage[wordindex(index)] |= markmask_calc(index);
}

void bit_clear(bitword_t* bitstorage, counter_t index) {
    bitstorage[wordindex(index)] &= ~markmask_calc(index);
}

// Helper functions for testing
void print_bits(bitword_t* bitstorage, counter_t start, counter_t end) {
    for (counter_t i = start; i <= end; i++) {
        printf("%d", bit_get(bitstorage, i) ? 1 : 0);
        if ((i+1) % 8 == 0) printf(" ");
    }
    printf("\n");
}

void set_pattern(bitword_t* bitstorage, counter_t start, counter_t size, const char* pattern) {
    for (counter_t i = 0; i < size; i++) {
        if (pattern[i % strlen(pattern)] == '1') {
            bit_set(bitstorage, start + i);
        } else {
            bit_clear(bitstorage, start + i);
        }
    }
}

bool verify_pattern(bitword_t* bitstorage, counter_t start, counter_t end, const char* pattern) {
    size_t pattern_len = strlen(pattern);
    for (counter_t i = start; i < end; i++) {
        bool expected = pattern[(i - start) % pattern_len] == '1';
        bool actual = bit_get(bitstorage, i);
        if (expected != actual) {
            printf("Pattern mismatch at bit %ju: expected %d, got %d\n", 
                   (uintmax_t)i, expected, actual);
            return false;
        }
    }
    return true;
}

// Test for continuePattern_smallSize with simple patterns
void test_continuePattern_smallSize() {
    printf("Testing continuePattern_smallSize...\n");
    
    const counter_t bitstorage_size = 256;
    bitword_t* bitstorage = (bitword_t*)calloc(wordindex(bitstorage_size) + 1, sizeof(bitword_t));
    
    // Test case 1: Simple alternating pattern
    const char* pattern1 = "1010";
    set_pattern(bitstorage, 10, 4, pattern1);
    
    // Extend the pattern
    continuePattern_smallSize(bitstorage, 10, 4, 50);
    
    // Verify the pattern was extended correctly
    bool result = verify_pattern(bitstorage, 14, 50, pattern1);
    assert(result);
    printf("  ✓ Simple alternating pattern test passed\n");
    
    // Test case 2: Pattern with odd size and offset
    memset(bitstorage, 0, (wordindex(bitstorage_size) + 1) * sizeof(bitword_t));
    const char* pattern2 = "10110";
    set_pattern(bitstorage, 23, 5, pattern2);
    
    continuePattern_smallSize(bitstorage, 23, 5, 100);
    
    result = verify_pattern(bitstorage, 28, 100, pattern2);
    assert(result);
    printf("  ✓ Pattern with odd size and offset test passed\n");
    
    free(bitstorage);
}

// Test for continuePattern_aligned
void test_continuePattern_aligned() {
    printf("Testing continuePattern_aligned...\n");
    
    const counter_t bitstorage_size = 512;
    const counter_t word_size = WORD_SIZE_BITS;
    bitword_t* bitstorage = (bitword_t*)calloc(wordindex(bitstorage_size) + 1, sizeof(bitword_t));
    
    // Create a pattern that's exactly one word long and aligned
    const counter_t pattern_start = word_size; // Start at a word boundary
    const counter_t pattern_size = word_size;  // One word size
    
    // Create a complex pattern
    for (counter_t i = 0; i < pattern_size; i++) {
        if (i % 3 == 0 || i % 5 == 0) {
            bit_set(bitstorage, pattern_start + i);
        }
    }
    
    // Extend the pattern
    continuePattern_aligned(bitstorage, pattern_start, pattern_size, pattern_start + pattern_size * 5);
    
    // Verify each copy of the pattern
    for (counter_t i = 1; i <= 4; i++) {
        for (counter_t j = 0; j < pattern_size; j++) {
            bool expected = bit_get(bitstorage, pattern_start + j);
            bool actual = bit_get(bitstorage, pattern_start + pattern_size * i + j);
            assert(expected == actual);
        }
    }
    
    printf("  ✓ Word-aligned pattern test passed\n");
    
    // Test with multi-word pattern
    memset(bitstorage, 0, (wordindex(bitstorage_size) + 1) * sizeof(bitword_t));
    
    const counter_t multi_pattern_start = word_size * 2;
    const counter_t multi_pattern_size = word_size * 3;
    
    // Create a pattern
    for (counter_t i = 0; i < multi_pattern_size; i++) {
        if ((i / 8) % 2 == 0) {
            bit_set(bitstorage, multi_pattern_start + i);
        }
    }
    
    // Extend the pattern
    continuePattern_aligned(bitstorage, multi_pattern_start, multi_pattern_size, 
                          multi_pattern_start + multi_pattern_size * 3);
    
    // Verify
    for (counter_t i = 1; i <= 2; i++) {
        for (counter_t j = 0; j < multi_pattern_size; j++) {
            bool expected = bit_get(bitstorage, multi_pattern_start + j);
            bool actual = bit_get(bitstorage, multi_pattern_start + multi_pattern_size * i + j);
            assert(expected == actual);
        }
    }
    
    printf("  ✓ Multi-word aligned pattern test passed\n");
    
    free(bitstorage);
}

// Test for continuePattern_shiftright
void test_continuePattern_shiftright() {
    printf("Testing continuePattern_shiftright...\n");
    
    const counter_t bitstorage_size = 512;
    bitword_t* bitstorage = (bitword_t*)calloc(wordindex(bitstorage_size) + 1, sizeof(bitword_t));
    
    // Create a pattern with a specific offset to ensure right shift
    const counter_t source_start = WORD_SIZE_BITS - 10;  // Near the end of first word
    const counter_t pattern_size = 20;  // Crossing word boundary
    
    // Set a simple pattern
    const char* pattern = "1100110011";
    set_pattern(bitstorage, source_start, pattern_size, pattern);
    
    // Ensure we have a right shift scenario (source_bit < copy_bit)
    const bitshift_t source_bit = bitindex_calc(source_start);
    const bitshift_t copy_bit = bitindex_calc(source_start + pattern_size);
    assert(source_bit < copy_bit); // Confirm right shift condition
    
    // Extend the pattern
    continuePattern_shiftright(bitstorage, source_start, pattern_size, source_start + pattern_size * 5);
    
    // Verify the pattern was extended correctly
    bool result = verify_pattern(bitstorage, source_start + pattern_size, 
                              source_start + pattern_size * 5, pattern);
    assert(result);
    
    printf("  ✓ Right shift pattern test passed\n");
    
    // Test single-word case
    memset(bitstorage, 0, (wordindex(bitstorage_size) + 1) * sizeof(bitword_t));
    
    const counter_t single_source = 12;
    const counter_t single_size = 8;
    set_pattern(bitstorage, single_source, single_size, "10101010");
    
    // Make sure the destination is in the same word
    continuePattern_shiftright(bitstorage, single_source, single_size, single_source + single_size);
    
    result = verify_pattern(bitstorage, single_source + single_size, 
                         single_source + single_size * 2, "10101010");
    assert(result);
    
    printf("  ✓ Single-word right shift test passed\n");
    
    free(bitstorage);
}

// Test for continuePattern_shiftleft
void test_continuePattern_shiftleft() {
    printf("Testing continuePattern_shiftleft...\n");
    
    const counter_t bitstorage_size = 512;
    bitword_t* bitstorage = (bitword_t*)calloc(wordindex(bitstorage_size) + 1, sizeof(bitword_t));
    
    // Create a pattern with a specific offset to ensure left shift
    const counter_t source_start = 10;  // In the middle of a word
    const counter_t pattern_size = WORD_SIZE_BITS;  // One word size
    
    // Make sure first word of source has some bits set
    bit_set(bitstorage, source_start);
    bit_set(bitstorage, source_start + 2);
    bit_set(bitstorage, source_start + 5);
    bit_set(bitstorage, source_start + 6);
    
    // And the second word too
    bit_set(bitstorage, source_start + WORD_SIZE_BITS - 5);
    bit_set(bitstorage, source_start + WORD_SIZE_BITS - 2);
    
    // Ensure we have a left shift scenario (source_bit > copy_bit)
    const counter_t copy_start = source_start + pattern_size;
    const bitshift_t source_bit = bitindex_calc(source_start);
    const bitshift_t copy_bit = bitindex_calc(copy_start);
    assert(source_bit > copy_bit); // Confirm left shift condition
    
    // Extend the pattern
    continuePattern_shiftleft(bitstorage, source_start, pattern_size, source_start + pattern_size * 4);
    
    // Verify by checking against the original pattern
    for (counter_t i = 0; i < pattern_size; i++) {
        bool expected = bit_get(bitstorage, source_start + i);
        for (counter_t copy = 1; copy <= 3; copy++) {
            bool actual = bit_get(bitstorage, source_start + pattern_size * copy + i);
            assert(expected == actual);
        }
    }
    
    printf("  ✓ Left shift pattern test passed\n");
    
    // Test left shift with unrolled function
    memset(bitstorage, 0, (wordindex(bitstorage_size) + 1) * sizeof(bitword_t));
    
    // Set up a longer pattern to exercise unrolling
    const counter_t unroll_size = WORD_SIZE_BITS * 4;
    for (counter_t i = 0; i < unroll_size; i++) {
        if ((i / 4) % 3 == 0) {
            bit_set(bitstorage, source_start + i);
        }
    }
    
    // Extend the larger pattern
    continuePattern_shiftleft(bitstorage, source_start, unroll_size, source_start + unroll_size * 2);
    
    // Verify
    for (counter_t i = 0; i < unroll_size; i++) {
        bool expected = bit_get(bitstorage, source_start + i);
        bool actual = bit_get(bitstorage, source_start + unroll_size + i);
        assert(expected == actual);
    }
    
    printf("  ✓ Left shift with unrolling test passed\n");
    
    free(bitstorage);
}

// Test for the main continuePattern function
void test_continuePattern_main() {
    printf("Testing main continuePattern function...\n");
    
    const counter_t bitstorage_size = 1024;
    bitword_t* bitstorage = (bitword_t*)calloc(wordindex(bitstorage_size) + 1, sizeof(bitword_t));
    
    // Test small size pattern
    const char* small_pattern = "101010";
    set_pattern(bitstorage, 17, 6, small_pattern);
    continuePattern(bitstorage, 17, 6, 100);
    bool result = verify_pattern(bitstorage, 23, 100, small_pattern);
    assert(result);
    printf("  ✓ Small size pattern delegation test passed\n");
    
    // Test right shift pattern
    memset(bitstorage, 0, (wordindex(bitstorage_size) + 1) * sizeof(bitword_t));
    const counter_t right_start = WORD_SIZE_BITS - 3;
    const counter_t right_size = WORD_SIZE_BITS + 5;
    
    // Set a pattern
    for (counter_t i = 0; i < right_size; i++) {
        if (i % 5 == 0 || i % 7 == 1) {
            bit_set(bitstorage, right_start + i);
        }
    }
    
    continuePattern(bitstorage, right_start, right_size, right_start + right_size * 3);
    
    // Verify by comparing each copy with the original
    for (counter_t i = 0; i < right_size; i++) {
        bool expected = bit_get(bitstorage, right_start + i);
        for (counter_t copy = 1; copy <= 2; copy++) {
            bool actual = bit_get(bitstorage, right_start + right_size * copy + i);
            assert(expected == actual);
        }
    }
    printf("  ✓ Right shift delegation test passed\n");
    
    // Test left shift pattern
    memset(bitstorage, 0, (wordindex(bitstorage_size) + 1) * sizeof(bitword_t));
    const counter_t left_start = 8;
    const counter_t left_size = WORD_SIZE_BITS + 10;
    
    // Set a pattern
    for (counter_t i = 0; i < left_size; i++) {
        if (i % 4 == 0 || i % 6 == 2) {
            bit_set(bitstorage, left_start + i);
        }
    }
    
    continuePattern(bitstorage, left_start, left_size, left_start + left_size * 3);
    
    // Verify
    for (counter_t i = 0; i < left_size; i++) {
        bool expected = bit_get(bitstorage, left_start + i);
        for (counter_t copy = 1; copy <= 2; copy++) {
            bool actual = bit_get(bitstorage, left_start + left_size * copy + i);
            assert(expected == actual);
        }
    }
    printf("  ✓ Left shift delegation test passed\n");
    
    // Test aligned pattern
    memset(bitstorage, 0, (wordindex(bitstorage_size) + 1) * sizeof(bitword_t));
    const counter_t aligned_start = WORD_SIZE_BITS * 2;
    const counter_t aligned_size = WORD_SIZE_BITS * 2;
    
    // Set a pattern
    for (counter_t i = 0; i < aligned_size; i++) {
        if (i % 3 == 1 || i % 8 == 5) {
            bit_set(bitstorage, aligned_start + i);
        }
    }
    
    continuePattern(bitstorage, aligned_start, aligned_size, aligned_start + aligned_size * 3);
    
    // Verify
    for (counter_t i = 0; i < aligned_size; i++) {
        bool expected = bit_get(bitstorage, aligned_start + i);
        for (counter_t copy = 1; copy <= 2; copy++) {
            bool actual = bit_get(bitstorage, aligned_start + aligned_size * copy + i);
            assert(expected == actual);
        }
    }
    printf("  ✓ Aligned delegation test passed\n");
    
    free(bitstorage);
}

int main() {
    printf("Running continuePattern unit tests...\n\n");
    
    test_continuePattern_smallSize();
    test_continuePattern_aligned();
    test_continuePattern_shiftright();
    test_continuePattern_shiftleft();
    test_continuePattern_main();
    
    printf("\nAll continuePattern tests passed!\n");
    return 0;
}