// generate_wheel_cache.c
// Generates a C header file containing pre-computed wheel data arrays.
// Usage: generate_wheel_cache <WHEEL_MAX> [output_file]
//   WHEEL_MAX: the highest prime number in the wheel (e.g. 5 for 8of30)
//   output_file: optional output path; defaults to stdout
//
// The generated header can be included by sieve_storage_wheel.h when
// WHEEL_USE_CACHE is defined, replacing the runtime build_wheel() call.

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

// Compute product of all primes up to max
static uint64_t wheel_size(int max) {
    uint64_t s = 1;
    for (int p = 2; p <= max; p++) {
        int is_prime = 1;
        for (int f = 2; f < p; f++) if (p % f == 0) { is_prime = 0; break; }
        if (is_prime) s *= p;
    }
    return s;
}

// Count primes up to max (Phi(2,3,...) = number of coprime residues)
static int count_stripes(int wheel_max, uint64_t wsize) {
    int count = 0;
    for (uint64_t i = 0; i < wsize; i++) {
        int masked = 0;
        for (int f = 2; f <= wheel_max; f++) {
            int is_prime = 1;
            for (int g = 2; g < f; g++) if (f % g == 0) { is_prime = 0; break; }
            if (!is_prime) continue;
            if ((i + wsize) % f == 0) { masked = 1; break; }
        }
        if (!masked) count++;
    }
    return count;
}

static int is_prime(int n) {
    if (n < 2) return 0;
    for (int f = 2; f < n; f++) if (n % f == 0) return 0;
    return 1;
}

int main(int argc, char *argv[]) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <WHEEL_MAX> [output_file]\n", argv[0]);
        fprintf(stderr, "  WHEEL_MAX: highest prime in wheel (e.g. 5 for 8of30, 7 for 48of210)\n");
        return 1;
    }

    int wheel_max = atoi(argv[1]);
    if (wheel_max < 2) {
        fprintf(stderr, "WHEEL_MAX must be >= 2\n");
        return 1;
    }

    FILE *out = stdout;
    if (argc >= 3) {
        out = fopen(argv[2], "w");
        if (!out) { perror("fopen"); return 1; }
    }

    uint64_t wsize = wheel_size(wheel_max);
    int stripes = count_stripes(wheel_max, wsize);
    int stripe_bytes = (stripes - 1) / 8 + 1;

    fprintf(stderr, "WHEEL_MAX=%d  WHEEL_SIZE=%llu  stripes=%d  stripe_bytes=%d\n",
            wheel_max, (unsigned long long)wsize, stripes, stripe_bytes);

    // Allocate arrays
    unsigned int *wheelprimes      = calloc(wheel_max + 1, sizeof(unsigned int));
    uint8_t      *wheelmask        = calloc(wsize, sizeof(uint8_t));
    uint8_t      *wheelmask_compr  = calloc(wsize, sizeof(uint8_t));
    uint8_t      *wheelmask_index  = calloc(wsize, sizeof(uint8_t));
    int64_t      *wheelmask_bpt    = malloc(wsize * sizeof(int64_t));

    if (!wheelprimes || !wheelmask || !wheelmask_compr || !wheelmask_index || !wheelmask_bpt) {
        fprintf(stderr, "Out of memory\n");
        return 1;
    }

    // Replicate build_wheel() logic exactly
    // Step 1: mark non-primes in wheelprimes
    for (int i = 0; i < wheel_max; i++) {
        wheelprimes[i] = 0;
        for (int f = 2; f < i; f++) {
            if (i % f == 0) { wheelprimes[i] = 1; break; }
        }
    }
    wheelprimes[wheel_max] = 0; // sentinel

    // Step 2: clear wheelmask (it's a packed bit array, so only wsize/8+1 bytes matter)
    for (uint64_t i = 0; i <= wsize / 8; i++) wheelmask[i] = 0;

    // Step 3: compute compressed wheel
    int64_t stripe_count = 0;
    for (uint64_t i = 0; i < wsize; i++) {
        wheelmask_compr[i] = 0;
        wheelmask_index[i] = 0;
        wheelmask_bpt[i]   = -1;

        // Check if divisible by any prime in the wheel
        for (int f = 2; f <= wheel_max; f++) {
            if (!is_prime(f)) continue;
            if ((i + wsize) % f == 0) {
                // mark in wheelmask packed bit array
                wheelmask[i / 8] |= (uint8_t)(1u << (i % 8));
                break;
            }
        }

        // If not masked: assign stripe
        if (!(wheelmask[i / 8] & (uint8_t)(1u << (i % 8)))) {
            wheelmask_compr[i] = (uint8_t)(1u << (stripe_count % 8));
            wheelmask_index[i] = (uint8_t)(stripe_count / 8);
            wheelmask_bpt[i]   = stripe_count + 1;
            stripe_count++;
        }
    }

    // Build name suffix: "<stripes>of<wsize>"
    char name_suffix[64];
    snprintf(name_suffix, sizeof(name_suffix), "%dof%llu", stripes, (unsigned long long)wsize);

    // Build include guard
    char guard[80];
    snprintf(guard, sizeof(guard), "WHEEL_CACHE_%s_H", name_suffix);
    for (char *p = guard; *p; p++) if (*p >= 'a' && *p <= 'z') *p -= 32;

    // ---- Emit header ----
    fprintf(out, "// Auto-generated wheel cache for WHEEL_MAX=%d, WHEEL_SIZE=%llu (%s)\n",
            wheel_max, (unsigned long long)wsize, name_suffix);
    fprintf(out, "// DO NOT EDIT - generated by tools/generate_wheel_cache.c\n");
    fprintf(out, "// Command: generate_wheel_cache %d\n\n", wheel_max);
    fprintf(out, "#ifndef %s\n#define %s\n\n", guard, guard);

    fprintf(out, "#include <stdint.h>\n\n");

    // Wheel parameters as macros
    fprintf(out, "#define WC_WHEEL_MAX         %d\n", wheel_max);
    fprintf(out, "#define WC_WHEEL_SIZE        %llu\n", (unsigned long long)wsize);
    fprintf(out, "#define WC_WHEEL_STRIPES     %d\n", stripes);
    fprintf(out, "#define WC_WHEEL_STRIPE_BYTES %d\n", stripe_bytes);
    fprintf(out, "#define WC_WHEEL_STRIPE_BITS  %d\n\n", stripe_bytes * 8);

    // wheelprimes
    fprintf(out, "static const unsigned int _wc_wheelprimes[%d] = {\n    ", wheel_max + 1);
    for (int i = 0; i <= wheel_max; i++) {
        fprintf(out, "%u", wheelprimes[i]);
        if (i < wheel_max) fprintf(out, ", ");
    }
    fprintf(out, "\n};\n\n");

    // wheelmask  (packed bit array, only first wsize/8+1 bytes meaningful)
    uint64_t mask_bytes = wsize / 8 + 1;
    fprintf(out, "// Packed bit array: wheelmask[i/8] bit (i%%8) is set if i is masked (divisible by a wheel prime)\n");
    fprintf(out, "static const uint8_t _wc_wheelmask[%llu] = {\n", (unsigned long long)wsize);
    for (uint64_t i = 0; i < wsize; i++) {
        if (i % 16 == 0) fprintf(out, "    ");
        fprintf(out, "0x%02x", wheelmask[i]);
        if (i + 1 < wsize) fprintf(out, ",");
        if ((i % 16 == 15) || (i + 1 == wsize)) fprintf(out, "\n");
        else fprintf(out, " ");
    }
    fprintf(out, "};\n\n");

    // wheelmask_compressed
    fprintf(out, "static const uint8_t _wc_wheelmask_compressed[%llu] = {\n", (unsigned long long)wsize);
    for (uint64_t i = 0; i < wsize; i++) {
        if (i % 16 == 0) fprintf(out, "    ");
        fprintf(out, "0x%02x", wheelmask_compr[i]);
        if (i + 1 < wsize) fprintf(out, ",");
        if ((i % 16 == 15) || (i + 1 == wsize)) fprintf(out, "\n");
        else fprintf(out, " ");
    }
    fprintf(out, "};\n\n");

    // wheelmask_index
    fprintf(out, "static const uint8_t _wc_wheelmask_index[%llu] = {\n", (unsigned long long)wsize);
    for (uint64_t i = 0; i < wsize; i++) {
        if (i % 16 == 0) fprintf(out, "    ");
        fprintf(out, "%3u", wheelmask_index[i]);
        if (i + 1 < wsize) fprintf(out, ",");
        if ((i % 16 == 15) || (i + 1 == wsize)) fprintf(out, "\n");
        else fprintf(out, " ");
    }
    fprintf(out, "};\n\n");

    // wheelmask_bitpoint (int32_t is sufficient; values are -1 or 1..stripes)
    fprintf(out, "static const int32_t _wc_wheelmask_bitpoint[%llu] = {\n", (unsigned long long)wsize);
    for (uint64_t i = 0; i < wsize; i++) {
        if (i % 16 == 0) fprintf(out, "    ");
        fprintf(out, "%5lld", (long long)wheelmask_bpt[i]);
        if (i + 1 < wsize) fprintf(out, ",");
        if ((i % 16 == 15) || (i + 1 == wsize)) fprintf(out, "\n");
        else fprintf(out, " ");
    }
    fprintf(out, "};\n\n");

    fprintf(out, "#endif /* %s */\n", guard);

    if (argc >= 3) fclose(out);

    free(wheelprimes);
    free(wheelmask);
    free(wheelmask_compr);
    free(wheelmask_index);
    free(wheelmask_bpt);

    return 0;
}
