import React from 'react';
import EventsPanel from '../EventsPanel';
import SettingsPanel from '../SettingsPanel';
import CanvasStage from './CanvasStage';
import CanvasLoadingOverlay from './CanvasLoadingOverlay';
import JoinedEventsWidget from './JoinedEventsWidget';
import DebugToolsPanel from './DebugToolsPanel';

export default function VisualizerMainContent({
  mode3D,
  isUiChromeVisible,
  isEventsPanelCollapsed,
  panelWidth,
  loadingOverlayPhase,
  steps,
  overlayBarPct,
  currentStep,
  selectedSteps,
  handleStepSelection,
  handleMultiStepSelect,
  stopPlayback,
  setPanelWidth,
  toggleEventsPanel,
  isAllEventsWidgetHidden,
  areWidgetsJoined,
  expandEventsPanelFromWidget,
  dockEventsWidgetToTopBar,
  dockEventsWidgetToDetailPanel,
  joinWidgets,
  timingFocusOp,
  setTimingFocusOp,
  revealStepRequest,
  eventTitleSettings,
  showEventTitleAboveCurrentDetail,
  containerRef,
  glCanvasRef,
  glyphCanvasRef,
  wrapperCanvasRef,
  mergedCamera3DContainerStyle,
  renderCanvasStyle,
  setEventTitleSettings,
  eventTitleStyle,
  currentStepBanner,
  surroundingEvents,
  currentStepData,
  goToStep,
  revealCurrentStepInPanel,
  setIsEventsPanelCollapsed,
  stepAnimSlidersContent,
  stepAnimSlidersDockedContent,
  splitWidgets,
  pinnedBitIndices,
  hoveredBitInfo,
  computeBitInfo,
  getVisibleBalloonStyles,
  balloonLiveLayout,
  cachelineSize,
  setPinnedBitIndices,
  isDetailOpen,
  toggleDetailPanel,
  detailHeight,
  pendingBannerDragStart,
  setPendingBannerDragStart,
  updateDetailHeight,
  detailWidth,
  setDetailWidth,
  playing,
  stepStats,
  storageModel,
  wheelDefinition,
  layoutSettings,
  benchmarkTimingData,
  openDetailInspector,
  isDetailInspectorOpen,
  detailInspectorMode,
  detailInspectorQuery,
  setDetailInspectorQuery,
  setIsDetailInspectorOpen,
  detailInspectorRows,
  filteredDetailInspectorRows,
  isTimingPanelOpen,
  setIsTimingPanelOpen,
  benchmarkTimingFileName,
  onImportBenchmarkTiming,
  onShowEventTitle,
  onOpenRawLog,
  currentStepSourceLine,
  sourceRef,
  allEventsTransportContent,
  introPhase,
  handleIntroTransitionEnd,
  isSingleEventWidgetRevealed,
  joinBannerRect,
  pushJoinedWidgetToEventsPanel,
  pushJoinedWidgetToDetailPanel,
  hideJoinedWidget,
  isDetailOpenRef,
  setIsDetailOpen,
  autoFitColumnCount,
  setLayoutSettings,
  setSettingsActiveTab,
  setCachelineSize,
  cachePreset,
  setCachePreset,
  isHeatMapEnabled,
  setIsHeatMapEnabled,
  cachelineAnnotation,
  setCachelineAnnotation,
  isPrimeOverlayEnabled,
  setIsPrimeOverlayEnabled,
  isRangeOverlayEnabled,
  rangeOverlayStart,
  rangeOverlayEnd,
  onRangeOverlayToggle,
  setRangeOverlayStart,
  setRangeOverlayEnd,
  isMultiplesOverlayEnabled,
  multiplesOverlayPrime,
  onMultiplesOverlayToggle,
  setMultiplesOverlayPrime,
  onRangeOverlayReset,
  onMultiplesOverlayReset,
  isMinimapVisible,
  setIsMinimapVisible,
  isWindowsPlatform,
  settingsTabRequest,
  isDebugToolsOpen,
  rendererRef,
  glRendererRef,
  camera3DRef,
  camera3DTransform,
  zoom,
  glDebugInfo,
  theme,
  debugLayerMode,
  setDebugLayerMode,
  debugGlOffsetX,
  setDebugGlOffsetX,
  debugGlOffsetY,
  setDebugGlOffsetY,
  debugGlAutoOffsetY,
  isDebugCalibrationMode,
  setIsDebugCalibrationMode,
  applyDebugSnapshot,
  forceGlRedraw,
  isMacPlatform,
}) {
  return (
    <div
      className={`main-content${mode3D ? ' mode-3d' : ''}${isUiChromeVisible ? ' ui-chrome-visible' : ' ui-chrome-hidden'}`}
      style={{ '--events-panel-width': `${isEventsPanelCollapsed ? 0 : panelWidth}px` }}
    >
      <CanvasLoadingOverlay
        loadingOverlayPhase={loadingOverlayPhase}
        steps={steps}
        overlayBarPct={overlayBarPct}
      />
      <EventsPanel
        steps={steps}
        currentStep={currentStep}
        selectedSteps={selectedSteps}
        onStepClick={handleStepSelection}
        onMultiStepSelect={handleMultiStepSelect}
        onUserScroll={stopPlayback}
        width={panelWidth}
        onWidthChange={setPanelWidth}
        panelCollapsed={isEventsPanelCollapsed}
        onToggleCollapse={toggleEventsPanel}
        isAllEventsWidgetHidden={isAllEventsWidgetHidden || areWidgetsJoined}
        onExpandPanelFromWidget={expandEventsPanelFromWidget}
        onDockWidgetToTopBar={dockEventsWidgetToTopBar}
        onDockWidgetToDetailPanel={dockEventsWidgetToDetailPanel}
        onJoinWidgets={joinWidgets}
        externalOpFilter={timingFocusOp}
        onExternalOpFilterConsumed={() => setTimingFocusOp('')}
        revealStepRequest={revealStepRequest}
        eventTitleVisible={eventTitleSettings.visible && !areWidgetsJoined}
        onShowEventTitle={showEventTitleAboveCurrentDetail}
      />
      <CanvasStage
        mode3D={mode3D}
        containerRef={containerRef}
        glCanvasRef={glCanvasRef}
        glyphCanvasRef={glyphCanvasRef}
        wrapperCanvasRef={wrapperCanvasRef}
        glActive={true}
        hideGlCanvas={false}
        camera3DContainerStyle={mergedCamera3DContainerStyle}
        renderCanvasStyle={renderCanvasStyle}
        eventTitleSettings={eventTitleSettings}
        setEventTitleSettings={setEventTitleSettings}
        eventTitleStyle={eventTitleStyle}
        currentStepBanner={currentStepBanner}
        surroundingEvents={surroundingEvents}
        currentStepData={currentStepData}
        currentStep={currentStep}
        goToStep={goToStep}
        revealCurrentStepInPanel={revealCurrentStepInPanel}
        isEventsPanelCollapsed={isEventsPanelCollapsed}
        setIsEventsPanelCollapsed={setIsEventsPanelCollapsed}
        stepAnimSlidersContent={stepAnimSlidersContent}
        stepAnimSlidersDockedContent={stepAnimSlidersDockedContent}
        areWidgetsJoined={areWidgetsJoined}
        onJoinWidgets={joinWidgets}
        onSplitWidgets={splitWidgets}
        pinnedBitIndices={pinnedBitIndices}
        hoveredBitInfo={hoveredBitInfo}
        computeBitInfo={computeBitInfo}
        getVisibleBalloonStyles={getVisibleBalloonStyles}
        balloonLiveLayout={balloonLiveLayout}
        cachelineSize={cachelineSize}
        setPinnedBitIndices={setPinnedBitIndices}
        handleStepSelection={handleStepSelection}
        isDetailOpen={isDetailOpen}
        toggleDetailPanel={toggleDetailPanel}
        detailHeight={detailHeight}
        pendingBannerDragStart={pendingBannerDragStart}
        onConsumePendingBannerDragStart={() => setPendingBannerDragStart(null)}
        updateDetailHeight={updateDetailHeight}
        detailWidth={detailWidth}
        setDetailWidth={setDetailWidth}
        playing={playing}
        selectedSteps={selectedSteps}
        stepStats={stepStats}
        storageModel={storageModel}
        wheelDefinition={wheelDefinition}
        layoutSettings={layoutSettings}
        benchmarkTimingData={benchmarkTimingData}
        openDetailInspector={openDetailInspector}
        isDetailInspectorOpen={isDetailInspectorOpen}
        detailInspectorMode={detailInspectorMode}
        detailInspectorQuery={detailInspectorQuery}
        setDetailInspectorQuery={setDetailInspectorQuery}
        setIsDetailInspectorOpen={setIsDetailInspectorOpen}
        detailInspectorRows={detailInspectorRows}
        filteredDetailInspectorRows={filteredDetailInspectorRows}
        isTimingPanelOpen={isTimingPanelOpen}
        setIsTimingPanelOpen={setIsTimingPanelOpen}
        benchmarkTimingFileName={benchmarkTimingFileName}
        setTimingFocusOp={setTimingFocusOp}
        onImportBenchmarkTiming={onImportBenchmarkTiming}
        steps={steps}
        onShowEventTitle={onShowEventTitle}
        onOpenRawLog={onOpenRawLog}
        currentStepSourceLine={currentStepSourceLine}
        hasRawSource={!!sourceRef}
        allEventsTransport={allEventsTransportContent}
        introPhase={introPhase}
        onIntroTransitionEnd={handleIntroTransitionEnd}
        isSingleEventWidgetRevealed={isSingleEventWidgetRevealed}
      />
      {areWidgetsJoined && isEventsPanelCollapsed && !isAllEventsWidgetHidden && eventTitleSettings.visible && isSingleEventWidgetRevealed && (
        <JoinedEventsWidget
          settings={eventTitleSettings}
          setSettings={setEventTitleSettings}
          banner={currentStepBanner}
          surrounding={surroundingEvents}
          currentStepData={currentStepData}
          revealCurrentStepInPanel={revealCurrentStepInPanel}
          sliders={stepAnimSlidersContent}
          onSplitWidgets={splitWidgets}
          onPushToEventsPanel={pushJoinedWidgetToEventsPanel}
          onPushToDetailPanel={pushJoinedWidgetToDetailPanel}
          initialBannerRect={joinBannerRect}
          onHideWidget={hideJoinedWidget}
          onNavigate={() => { if (!isDetailOpenRef.current) setIsDetailOpen(true); }}
        />
      )}
      <SettingsPanel
        settings={layoutSettings}
        onChange={setLayoutSettings}
        autoFitColumns={autoFitColumnCount}
        onActiveTabChange={setSettingsActiveTab}
        cachelineSize={cachelineSize}
        onCachelineSizeChange={setCachelineSize}
        cachePreset={cachePreset}
        onCachePresetChange={setCachePreset}
        isHeatMapEnabled={isHeatMapEnabled}
        onHeatMapToggle={setIsHeatMapEnabled}
        cachelineAnnotation={cachelineAnnotation}
        onCachelineAnnotationChange={setCachelineAnnotation}
        isPrimeOverlayEnabled={isPrimeOverlayEnabled}
        onPrimeOverlayToggle={setIsPrimeOverlayEnabled}
        isRangeOverlayEnabled={isRangeOverlayEnabled}
        rangeOverlayStart={rangeOverlayStart}
        rangeOverlayEnd={rangeOverlayEnd}
        onRangeOverlayToggle={onRangeOverlayToggle}
        onRangeOverlayStartChange={setRangeOverlayStart}
        onRangeOverlayEndChange={setRangeOverlayEnd}
        isMultiplesOverlayEnabled={isMultiplesOverlayEnabled}
        multiplesOverlayPrime={multiplesOverlayPrime}
        onMultiplesOverlayToggle={onMultiplesOverlayToggle}
        onMultiplesOverlayPrimeChange={setMultiplesOverlayPrime}
        onRangeOverlayReset={onRangeOverlayReset}
        onMultiplesOverlayReset={onMultiplesOverlayReset}
        isMinimapVisible={isMinimapVisible}
        onShowMinimapChange={setIsMinimapVisible}
        minimapControlVisible={true}
        eventTitleSettings={eventTitleSettings}
        onEventTitleSettingsChange={setEventTitleSettings}
        outlineSettings={layoutSettings.outlines}
        onOutlineChange={(outlines) => setLayoutSettings((prev) => ({ ...prev, outlines }))}
        isWindowsPlatform={isWindowsPlatform}
        showAnimationControls={true}
        activeTabRequest={settingsTabRequest}
      />
      {isDebugToolsOpen && (
        <DebugToolsPanel
          rendererRef={rendererRef}
          glCanvasRef={glCanvasRef}
          glRendererRef={glRendererRef}
          camera3DRef={camera3DRef}
          camera3DTransform={camera3DTransform}
          zoomLevel={zoom}
          glDebugInfo={glDebugInfo}
          theme={theme}
          debugLayerMode={debugLayerMode}
          setDebugLayerMode={setDebugLayerMode}
          debugGlOffsetX={debugGlOffsetX}
          setDebugGlOffsetX={setDebugGlOffsetX}
          debugGlOffsetY={debugGlOffsetY}
          setDebugGlOffsetY={setDebugGlOffsetY}
          debugGlAutoOffsetY={debugGlAutoOffsetY}
          isDebugCalibrationMode={isDebugCalibrationMode}
          setIsDebugCalibrationMode={setIsDebugCalibrationMode}
          onApplyDebugSnapshot={applyDebugSnapshot}
          onForceGlRedraw={forceGlRedraw}
          rightOffset={isSettingsCollapsed ? 8 : (isMacPlatform ? 388 : 328)}
        />
      )}
    </div>
  );
}
