FROM alpine:3.21.3

# Install necessary dependencies
RUN apk add build-base mimalloc2-dev bash

# Set mimalloc as the default memory allocator using LD_PRELOAD
ENV LD_PRELOAD=/usr/lib/libmimalloc.so

WORKDIR /home/primes

# Copy all shell scripts, C source, and header files
COPY *.sh *.c *.h ./

# Copy the additional directory structure
COPY src/ ./src

# Ensure the bin directory exists
RUN mkdir -p bin

RUN chmod +x ./*.sh
RUN sed -i 's/\r$//' *.sh

# RUN ./compile.sh

ENTRYPOINT [ "./test.sh" ]

