WORKDIR /home/sieve

# Copy all shell scripts, C source, and header files
COPY src/ ./src/
COPY tools/ ./tools/

# Copy builder
COPY sieve ./sieve

# Ensure the bin directory exists
RUN mkdir -p bin

# Make the sieve executable and resolve LF/CRLF issues
RUN chmod +x ./tools/* ./sieve
RUN sed -i 's/\r$//' ./tools/* ./sieve

ENTRYPOINT [ "./sieve" ]
