FROM debian:buster-slim as builder

RUN apt-get update \
    && apt install build-essential -y

WORKDIR /home/primes

# Copy all shell scripts, C source, and header files
COPY *.sh *.c *.h ./

# Copy the additional directory structure
COPY src/ ./src

# Ensure the bin directory exists
RUN mkdir -p bin

RUN chmod +x ./*.sh
RUN sed -i 's/\r$//' *.sh

# RUN ./compile.sh

ENTRYPOINT [ "./test.sh" ]
