// Auto-generated wheel cache for WHEEL_MAX=3, WHEEL_SIZE=6 (2of6)
// DO NOT EDIT - generated by tools/generate_wheel_cache.c
// Command: generate_wheel_cache 3

#ifndef WHEEL_CACHE_2OF6_H
#define WHEEL_CACHE_2OF6_H

#include <stdint.h>

#define WC_WHEEL_MAX         3
#define WC_WHEEL_SIZE        6
#define WC_WHEEL_STRIPES     2
#define WC_WHEEL_STRIPE_BYTES 1
#define WC_WHEEL_STRIPE_BITS  8

static const unsigned int _wc_wheelprimes[4] = {
    0, 0, 0, 0
};

// Packed bit array: wheelmask[i/8] bit (i%8) is set if i is masked (divisible by a wheel prime)
static const uint8_t _wc_wheelmask[6] = {
    0x1d, 0x00, 0x00, 0x00, 0x00, 0x00
};

static const uint8_t _wc_wheelmask_compressed[6] = {
    0x00, 0x01, 0x00, 0x00, 0x00, 0x02
};

static const uint8_t _wc_wheelmask_index[6] = {
      0,   0,   0,   0,   0,   0
};

static const int32_t _wc_wheelmask_bitpoint[6] = {
       -1,     1,    -1,    -1,    -1,     2
};

#endif /* WHEEL_CACHE_2OF6_H */
