// Auto-generated wheel cache for WHEEL_MAX=5, WHEEL_SIZE=30 (8of30)
// DO NOT EDIT - generated by tools/generate_wheel_cache.c
// Command: generate_wheel_cache 5

#ifndef WHEEL_CACHE_8OF30_H
#define WHEEL_CACHE_8OF30_H

#include <stdint.h>

#define WC_WHEEL_MAX         5
#define WC_WHEEL_SIZE        30
#define WC_WHEEL_STRIPES     8
#define WC_WHEEL_STRIPE_BYTES 1
#define WC_WHEEL_STRIPE_BITS  8

static const unsigned int _wc_wheelprimes[6] = {
    0, 0, 0, 0, 1, 0
};

// Packed bit array: wheelmask[i/8] bit (i%8) is set if i is masked (divisible by a wheel prime)
static const uint8_t _wc_wheelmask[30] = {
    0x7d, 0xd7, 0x75, 0x1f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};

static const uint8_t _wc_wheelmask_compressed[30] = {
    0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x04, 0x00, 0x08, 0x00, 0x00,
    0x00, 0x10, 0x00, 0x20, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80
};

static const uint8_t _wc_wheelmask_index[30] = {
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0
};

static const int32_t _wc_wheelmask_bitpoint[30] = {
       -1,     1,    -1,    -1,    -1,    -1,    -1,     2,    -1,    -1,    -1,     3,    -1,     4,    -1,    -1,
       -1,     5,    -1,     6,    -1,    -1,    -1,     7,    -1,    -1,    -1,    -1,    -1,     8
};

#endif /* WHEEL_CACHE_8OF30_H */
