#include "../generic/setsuffix.h"
#define KEEP_VARIANT
#include "../bitstorage/bitstorage_applyMask.h"
#include "../bitstorage/bitstorage_setBitsTrue_largestep.h" 
#include "../bitstorage/bitstorage_setBitsTrue_smallstep_rotate.h" 
#include "../bitstorage/bitstorage_setBitsTrue_smallstep_totalshift.h" 
#include "../bitstorage/bitstorage_setBitsTrue_smallstep_rotate_pair.h" 
#include "../bitstorage/bitstorage_setBitsTrue_smallstep_rotate_pairv2.h" 
#include "../bitstorage/bitstorage_setBitsTrue_smallstep_rotate_pairv3.h" 
#undef KEEP_VARIANT
#include "../generic/cleansuffix.h"
